version: 2
jobs:
  build_test:
    docker:
     - image: ubuntu:18.04
    steps:
     # install dependencies
     # TODO (Chenyao): I'm not sure which packages are useful. Trim unused packages to speed up.
     - run: apt-get -y update &&
            apt-get -y install
              build-essential
              clang-8
              clang-format-8
              clang-tidy-8
              cmake
              doxygen
              git
              g++-7
              libjemalloc-dev
              llvm-8
              pkg-config
              valgrind
     - checkout
     - run: mkdir build
     - run: cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
     # 2020-12-01: We only want to buid with 2 cores to prevent us from running out of memory
     - run: cd build && make -j 2 
     - run: cd build && make check-lint
     - run: cd build && make check-clang-tidy
     - run: cd build && make check-tests

workflows:
  version: 2
  workflow:
    jobs:
      - build_test
